name: Scan GitHub Repo

on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Scan GitHub Repo
      run: |
        sudo apt-get update
        sudo apt-get install -y lynis
        lynis audit https://github.com/kupadhyay1212/azure-app-register
    - name: Store Scan Results
      uses: actions/upload-artifact@v2
      with:
        name: scan-results
        path: /var/log/lynis-report.dat
