on: push
name: Find Secrets
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: max/secret-scan@master
env:
  git-credential-helper: yes
phases:
  install:
    commands:
      - echo "in the install phase"
      - apt-get update && apt-get -y install jq python3-pip python3-dev && pip3 install --upgrade awscli
    finally:
      - echo This always runs even if the login command fails 
  pre_build:
    commands:
      - echo "Setting CodeCommit Credentials"
  build:
    commands:
      - echo "Build started on $(date)"
      - git clone https://github.com/awslabs/git-secrets
      - cd git-secrets
      - make install
      - cd $CODEBUILD_SRC_DIR
      - git clone https://github.com/signetic-mvs/healthcommons/tree/dev/.github/workflows
      - cd $CODECOMMIT_REPO_NAME && ls -lrt
      - git secrets --install
      - git secrets --register-aws
      ## Adding additional patterns, for example password
      #- git secrets --add password\s*=\s*.+
      - git secrets --scan --recursive
  post_build:
    commands:
      - echo "Build completed on $(date)"
artifacts:
  type: zip
  files: '**/*'
