name: TruffleHog Scan

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run TruffleHog scan
        uses: deepfence/gh-action-trufflehog@v1
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          scan_paths: '.'
          custom_rules_path: 'path/to/rules.json'
          scan_entropy: false
          scan_regex: true
